### ISSUE TITLE
Generation of json files

### ISSUE THREAD

**Issue by vighneshbirodkar** [tomfunkhouser/gaps#1]
Hello

I am using the gaps framework as a part of the [SUNCGToolbox](https://github.com/shurans/SUNCGtoolbox). Inside the dataset there are many `.json` files which `scn2img`, `scnview` and `scninfo` can recognize and render. How do I create my own similar `.json` file ? Are there conversion tools to convert from existing 3d models formats to the required `.json` format ? Also does `gaps` allow me to create a similar `.json` file containing just one object which I can get from a `.obj` file ?

**Comment by tomfunkhouser** [comment]
I am not aware of any tools to convert to the SUNCG .json format.

However, you probably don't need to.   The apps you list (scn2img, 
scnview, and scninfo) also read .obj files (including the .obj files for 
individual objects).   So, maybe you can use .obj format for 
scenes/objects you create yourself.

**Comment by vighneshbirodkar** [comment]
Thanks for the prompt reply @tomfunkhouser . The code by you are your collaborators seems to be very well written. However, I found myself a little lost sometimes due to the lack of documentation. 

I was able to view an `.obj` file with `scnview`.  Is there any way I can transform the loaded `.obj` file ? I want to be able to rotate and translate it. Maybe some other tools in conjunction can help me to achieve that ?

**Comment by tomfunkhouser** [comment]
scn2scn input.obj output.obj -rx <degrees> (or other transformations 
found in ParseArgs of apps/scn2scn.cpp)

**Comment by vighneshbirodkar** [comment]
@tomfunkhouser 
Is it possible to change the lighting while viewing an obj file ?

**Comment by tomfunkhouser** [comment]
Only if you program it yourself.

**Comment by vighneshbirodkar** [comment]
Hello, I was able to adjust lighting by creating custom light files. Is there any way the framework will allow me to modify scenes ? Like adding and deleting objects ?

**Comment by tomfunkhouser** [comment]
There is not an interactive program in the tool set to edit scenes.   
You could convert them to .obj with "scn2scn house.json output.obj" and 
then edit with other tools ...
