### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by Hoototo** [tomfunkhouser/gaps#2]
I compile the GAPS library, and there are some errors. The output of the compiled information is very long. So, I output it to a log file. Some problems list below.

make[5]: Entering directory `/home/hoo104/3dmatch-toolbox/gaps/apps/pfm2pfm'
make[5]: *** No rule to make target `../../pkgs/CSparse/*.h', needed by `pfm2pfm.o'.  Stop.
make[5]: Leaving directory `/home/hoo104/3dmatch-toolbox/gaps/apps/pfm2pfm'
make[4]: *** [opt] Error 2
make[4]: Leaving directory `/home/hoo104/3dmatch-toolbox/gaps/apps/pfm2pfm'
make[3]: *** [target] Error 2
make[3]: Leaving directory `/home/hoo104/3dmatch-toolbox/gaps/apps'
make[2]: *** [opt] Error 2
make[2]: Leaving directory `/home/hoo104/3dmatch-toolbox/gaps/apps'
make[1]: *** [target] Error 2
make[1]: Leaving directory `/home/hoo104/3dmatch-toolbox/gaps'
make: *** [opt] Error 2

![1](https://cloud.githubusercontent.com/assets/19700374/24285298/814b970c-10aa-11e7-8bfc-ebb6e0f2a034.png)

**Comment by Hoototo** [comment]
[out.log.zip](https://github.com/tomfunkhouser/gaps/files/867197/out.log.zip)

**Comment by tomfunkhouser** [comment]
Hoototo.  I cannot open a zip file.   So, please send the errors inline 
directly in an email.   Thanks.

**Comment by happyfrank** [comment]
I have the compiling problem to. 
I search the folder pkgs that can't a file or folder named CSparse.

**Comment by shuishui602** [comment]
I met the same compiling problem , have you solved it? @Hoototo @happyfrank

**Comment by tomfunkhouser** [comment]
CSparse is only used if RN_USE_CSPARSE is defined.
Can you post the compile error indicating from where CSparse is being referenced?

**Comment by shuishui602** [comment]
make[5]: Leaving directory `/home/shi/tools/3dmatch-toolbox/gaps/apps/scnview'
make[4]: Leaving directory `/home/shi/tools/3dmatch-toolbox/gaps/apps/scnview'
cd pfm2pfm; make opt
make[4]: Entering directory `/home/shi/tools/3dmatch-toolbox/gaps/apps/pfm2pfm'
make ../../bin/x86_64/pfm2pfm "CFLAGS=-DRN_USE_CSPARSE  -Wall -I. -I../../pkgs  -O3 -DNDEBUG" "LDFLAGS= -L../../lib/x86_64 -O "
make[5]: Entering directory `/home/shi/tools/3dmatch-toolbox/gaps/apps/pfm2pfm'
make[5]: *** No rule to make target `../../pkgs/CSparse/*.h', needed by `pfm2pfm.o'.  Stop.
make[5]: Leaving directory `/home/shi/tools/3dmatch-toolbox/gaps/apps/pfm2pfm'
make[4]: *** [opt] Error 2
make[4]: Leaving directory `/home/shi/tools/3dmatch-toolbox/gaps/apps/pfm2pfm'
make[3]: *** [target] Error 2
make[3]: Leaving directory `/home/shi/tools/3dmatch-toolbox/gaps/apps'
make[2]: *** [opt] Error 2
make[2]: Leaving directory `/home/shi/tools/3dmatch-toolbox/gaps/apps'
make[1]: *** [target] Error 2
make[1]: Leaving directory `/home/shi/tools/3dmatch-toolbox/gaps'
make: *** [opt] Error 2

**Comment by Hoototo** [comment]
You can look andy's answer
https://github.com/andyzeng/3dmatch-toolbox/issues/2#issuecomment-289919224
