### ISSUE TITLE
non-standard way to return string in R3SceneNode:: Info

### ISSUE THREAD

**Issue by yscoffee** [tomfunkhouser/gaps#6]
Hi,
I found this kind of usage which invokes returning a pointer to the temporary object, whose lifetime is NOT guaranteed..

https://github.com/tomfunkhouser/gaps/blob/master/pkgs/R3Graphics/R3SceneNode.h#L232
```
inline const char *R3SceneNode::
Info(const char *key) const
{
  // Return info associated with key
  const char *value = NULL;
  if (!info.Find(key, &value)) return NULL;
                     ^^^^^
  return value;
}

```

https://github.com/tomfunkhouser/gaps/blob/master/pkgs/R3Graphics/R3Scene.cpp#L4375

**Comment by tomfunkhouser** [comment]
The function returns a const pointer to a string stored within the info field of the R3SceneNode, which is persistent until it is specifically removed/deleted.   

Passing"&value" to info.Find as highlighted in your post is simply a way to extract a pointer to a string associated with the info class.   The function passes "&value" to info.Find, but it does not return "&value".   It returns "value", and so there should not be a problem with returning a pointer to the temporary object, whose lifetime is NOT guaranteed.

Am I missing something here?

**Comment by yscoffee** [comment]
the field of R3SceneNode also pointed to temporary object.
RNSymbolTable<const char *> info;
which can be traced back to a temporary buff at L4338 right?
https://github.com/tomfunkhouser/gaps/blob/master/pkgs/R3Graphics/R3Scene.cpp#L4338

**Comment by tomfunkhouser** [comment]
No.   New memory is allocated for the value string when it is inserted into the map at line 4346.

values.Insert(RNStrdup(token));

**Comment by yscoffee** [comment]
oh ok, you are correct. Thanks for the clarification.
btw where will the memory be free?, looks multiple nodes will now own the same pointer (point to model_id etc)

**Comment by tomfunkhouser** [comment]
The memory for the (large set of) data associated with a R3Scene are not freed when the R3Scene is deleted.   In theory, it is the responsibility of the application to delete and remove everything associated with a R3Scene before it is deleted.   In practice, R3Scenes are usually created and never deleted in the gaps apps, so far.
